### ISSUE TITLE
fight the disposable automation with an anti-automation 

### ISSUE THREAD

**Issue by martenson** [disposable-email-domains/disposable-email-domains#273]
If the https://web1.temp-mail.org/request/domains/format list is something that is fairly stable we could implement a CI check that automatically merges domains in that list with our blocklist.

```xml
<xml>
<item>@64ge.com</item>
<item>@brayy.com</item>
<item>@frnla.com</item>
<item>@geekale.com</item>
</xml>
```

**Comment by SufiSR** [comment]
> If the https://web1.temp-mail.org/request/domains/format list is something that is fairly stable we could implement a CI check that automatically merges domains in that list with our blocklist.
> 
> ```
> <xml>
> <item>@64ge.com</item>
> <item>@brayy.com</item>
> <item>@frnla.com</item>
> <item>@geekale.com</item>
> </xml>
> ```

The endpoint is stable but tends to outdate quickly. It also lists only four disposable mails although there are more than just those four.

**Comment by martenson** [comment]
@SufiSR I thought of something like a daily CI run - those listed there seem to be live which makes them valuable to us. Maybe we could look for more endpoint like this.

**Comment by DanielAbsi** [comment]
Hey @martenson,
Do you also have the URL for, emailondeck.com domain to be blocked like you did with temp-mail.com?

**Comment by DanielAbsi** [comment]
Link is down for https://web1.temp-mail.org/request/domains/format

**Comment by martenson** [comment]
elaborated the issue in https://github.com/disposable-email-domains/disposable-email-domains/issues/450
