### ISSUE TITLE
Add metalunits.com

### ISSUE THREAD

**Issue by rdsedmundo** [disposable-email-domains/disposable-email-domains#288]
We've had 100s of accounts registering in our service with this e-mail domain with random characters.

**Comment by martenson** [comment]
Could you please report the incident to the contact they provide on metalunits.com? If they do not respond and explain I'll be ok with adding `metalunits.com` to the list I think.

> If you have some troubles with user registrations simply ban them by IP address, don't ban our domain names, we're not a throwaway email service and your emails won't bounce!
> All abuse reporting can be done via abuse@smtp.dev

**Comment by russorat** [comment]
looks like their mx records point to https://mail.tm/en/ which is definitely disposable: 

<img width="747" alt="image" src="https://user-images.githubusercontent.com/4805997/156308843-a0351b20-3204-487f-8ad2-e5361d557605.png">

Closed by https://github.com/disposable-email-domains/disposable-email-domains/pull/314

**Comment by HenkPoley** [comment]
Same nonsense about never sending spam http[:]//candassociates[.]com/

(But it's used for receiving from spam targets.)
