### ISSUE TITLE
Please remove my *personal* domain from this list

### ISSUE THREAD

**Issue by shitware-nl** [disposable-email-domains/disposable-email-domains#300]
Please remove shitware.nl . Used as a personal catch-all, but not a public disposable email domain. Try me by sending a nonce to {whatever}@shitware.nl .

Thanks.

**Comment by shitware-nl** [comment]
Thanks!

**Comment by martenson** [comment]
@shitware-nl Not sure how long you have the domain, but in case it's been a while please accept my apologies for putting you on this list in the first place.
