### ISSUE TITLE
Fuck all of you idiots

### ISSUE THREAD

**Issue by woshiniming007** [disposable-email-domains/disposable-email-domains#303]
You guys think you're doing something rewarding? Helping companies harass users?

**Comment by DanielAbsi** [comment]
Hello @woshiniming007,

I use a lot disposable email too I understand your angreness. Companies are looking to solutions to avoid having there’s  email bouncing all the time. They only what to email real people and real customers.
Some people, have their own disposable email only for them where you can follow [this article by free codecamp](https://www.freecodecamp.org/news/how-to-setup-your-own-disposable-email-server-b4cfd297afa7/)
or an other solution 100% is creating a few proton mail. You can create as much as you want, and proton mail have a good reputation too. 

Best,
