### ISSUE TITLE
Temp mail disposable emails

### ISSUE THREAD

**Issue by DanielAbsi** [disposable-email-domains/disposable-email-domains#316]
**temp-mail.org**
_______________________
tonaeto.com
songsign.com
superyp.com

**Comment by DanielAbsi** [comment]
Also Add http://findtempmail.com/

.....@chenbot.email
.....@pipemail.space

**Comment by DanielAbsi** [comment]
I find a way to detect potential disposable email from temp-mail.org by filtering them. 
All temp-mail.org email have the same pattern and if the pattern is found manual detection is easier to detecting them: 
_________________
All temp-mail.org email is a .com domain name. 
All temp-mail.org the Registrar is NameSilo, LLC.
All temp-mail.org is Registered On 2018-01-31, Updated On 2022-03-03 and Expires On 2023-01-31.
All temp-mail.org use the Name Server (NS): NS1.DNSOWL.COM
All temp-mail.org have setup a DMARC Record with this exact signature:
`v=DMARC1; p=reject; rua=mailto:reporterdmarc@yandex.ru; ruf=mailto:reporterdmarc@yandex.ru; rf=afrf; sp=reject; fo=1; pct=100; ri=604800; adkim=s; aspf=s`

**Comment by martenson** [comment]
@DanielAbsi I like the idea! Forging this into a github action workflow would be very useful I think.
