### ISSUE TITLE
PyPI License Alignment

### ISSUE THREAD

**Issue by elhanan-mishraky** [disposable-email-domains/disposable-email-domains#346]
Hi, I see in PyPI that the package is licensed under MIT License, will it be possible to put the MIT license also here?

**Comment by martenson** [comment]
Hi @elhanan-mishraky

The pypi package [repo](https://github.com/disposable-email-domains/python-disposable-email-domains) is under MIT. 

This repo is under https://creativecommons.org/publicdomain/zero/1.0/ as per readme but I will add LICENSE.txt to make sure people will notice. Thanks.
