### ISSUE TITLE
A few more

### ISSUE THREAD

**Issue by numbofathma** [disposable-email-domains/disposable-email-domains#444]
`[
  'imagepoet.net',
  'pelagius.net',
  'closetab.email',
  'gosarlar.com',
  'namewok.com',
  'secretmail.net',
  'mitico.org',
  'cashbenties.com',
  'tippabble.com',
  'dealoaks.com',
  'vigoneo.com',
  'vvesavedfa.com',
  'gotgel.org',
  'jollyfree.com',
  'rungel.net',
  'code-gmail.com',
  'videotoptop.com',
  'zabpq@ipxwan.com',
]`

**Comment by martenson** [comment]
https://github.com/disposable-email-domains/disposable-email-domains?tab=readme-ov-file#contributing
