### ISSUE TITLE
Below domain is missing 

### ISSUE THREAD

**Issue by vishad-p-gortnm** [disposable-email-domains/disposable-email-domains#457]
Hello Guys

imimail.me - This is new domain which is missing in your list this is recently used in one of my application please add it in list

**Comment by haumacher** [comment]
Hi @vishad-p-gortnm ,

it seems that the domain `imimail.me` cannot receive e-mail at all. It has neither a MX record assigned nor is a fallback mail server resolvable. Are you sure that a registration with an e-mail from that domain really succeeded?

```
> dig +nocomments +nocmd +noquestion +nostats +norrcomment imimail.me MX
me.			3021	IN	SOA	a0.nic.me. hostmaster.donuts.email. 1709793714 7200 900 1209600 3600

> dig +nocomments +nocmd +noquestion +nostats +norrcomment imimail.me
me.			3030	IN	SOA	a0.nic.me. hostmaster.donuts.email. 1709793714 7200 900 1209600 3600
```

**Comment by vishad-p-gortnm** [comment]
sorry it was domain name - 'mimimail.me

**Comment by haumacher** [comment]
I can confirm this, my [heuristics](https://github.com/haumacher/disposable-email-domains/blob/master/HEURISTICS.md) says:

```
mimimail.me: ["DomainInfo",{"service":"https://dropmail.me","potentialServices":[],"mailServers":["mx.mimimail.me"],"kind":"disposable","heuristics":"ip-address"}]
```

Uses same mail server IP as other domains from `https://dropmail.me`.

**Comment by martenson** [comment]
@vishad-p-gortnm Would you mind creating a pull request for this addition?
