### ISSUE TITLE
Add simplelogin.com

### ISSUE THREAD

**Issue by Emalton** [disposable-email-domains/disposable-email-domains#476]
Emails on the simplelogin.com domain are disposable.

**Comment by martenson** [comment]
Those seem to be aliases that you get _after_ you register. I am not sure this qualifies as disposable in our book.

**Comment by pluja** [comment]
I personally don't think SimpleLogin or AnonAddy should be classified as disposable emails. These services allow users to create proxy email addresses that forward messages to their main email inbox. They serve as a privacy tool, enabling users to avoid sharing their personal email addresses directly and control spam or email leaks.

By using a unique email address for each service I register with, I can identify which service sends me spam or has leaked my address to other companies. This allows me to disable a specific address that is sending too much spam or has been compromised. While similar control could be achieved with email filters, the added layer of privacy and control provided by these services is significant.

Therefore, I don't believe these should be considered disposable emails.

**Comment by jnv** [comment]
Simplelogin is an email relay service, not a disposable email service. Previous PR to add it was rejected: https://github.com/disposable-email-domains/disposable-email-domains/pull/252
