### ISSUE TITLE
domains hidelux.com / aersm.com

### ISSUE THREAD

**Issue by cuypz** [disposable-email-domains/disposable-email-domains#482]
These two have been popping up on my webshop lately:

hidelux.com
aersm.com

**Comment by Daniel3356** [comment]
Both domaine have an `MX` that point to `mail-data.net`

**Comment by cuypz** [comment]
https://verifymail.io/domain/aersm.com

https://verifymail.io/domain/hidelux.com

**Comment by martenson** [comment]
These do not see available anymore (sorry for the delay) and we do not cannibalize other lists. Thanks for help though.
