### ISSUE TITLE
allowlist containing suspicious domains

### ISSUE THREAD

**Issue by matthiaaas** [disposable-email-domains/disposable-email-domains#484]
What exactly is the justification for domains to fall into the `allowlist.conf`? A quick scan through that file made me find a bunch of very suspicious domains like

- https://github.com/disposable-email-domains/disposable-email-domains/blob/master/allowlist.conf#L81
- https://github.com/disposable-email-domains/disposable-email-domains/blob/master/allowlist.conf#L80
- https://github.com/disposable-email-domains/disposable-email-domains/blob/master/allowlist.conf#L29

that almost all went in through commit e6158a3.

**Comment by martenson** [comment]
they were not disposable at the time, hence removed. Some explanation here: https://github.com/disposable-email-domains/disposable-email-domains/pull/28
