### ISSUE TITLE
add mailfast.pro and add disposable emails from gmail.com

### ISSUE THREAD

**Issue by Botato300** [disposable-email-domains/disposable-email-domains#492]
This domain is also for disposable mails: [maildrop.pro](https://incognitomail.co/)

There is also a site called [emailnator](https://www.emailnator.com/) where you can get gmail.com emails, it would be a good idea to web scrape emailnator.com to get all the gmail.com emails they use and add them to the blacklist. You can also get emails from other domains such as googlemail.com, tmpmailtor, etc.

**Comment by martenson** [comment]
I added the new ones from emailinator. For obvious reasons we cannot recommend blocking google domains
