### ISSUE TITLE
Remove Kennedy808.com from list of disposable domains

### ISSUE THREAD

**Issue by MegaDude808** [disposable-email-domains/disposable-email-domains#505]
Hello, I am requesting to have Kennedy808.com removed from the list. 

I used the domain for personal use with a temporary email service years ago, but now it's my daily-use email.

Thanks

**Comment by martenson** [comment]
@MegaDude808 you are a new account with no history, do you have anything to support your claim?

**Comment by MegaDude808** [comment]
Here's a screenshot from my Google admin console showing the Kennedy808.com domain as an alias for my main Kennedy.us domain. I used to use the Kennedy.us for my emails but I switched to the Kennedy808.com.

Does that work?

<img width="1410" alt="image" src="https://github.com/user-attachments/assets/2a815cf7-69d6-467f-915d-5f66ca06781b">

**Comment by MegaDude808** [comment]
Just checking in. Is there anything else I need to do?

Thanks

**Comment by MegaDude808** [comment]
Here are a couple more screenshots showing my ownership of the domain, and the MX records being pointed to my Google Workspace account.

Thanks

![domains2](https://github.com/user-attachments/assets/8036ba97-e4a4-47f0-ad94-487fc2b9de14)
<img width="1233" alt="domains3" src="https://github.com/user-attachments/assets/08a66fc7-1fe6-4dea-9993-d31344fd085f">

**Comment by martenson** [comment]
@MegaDude808 you got it, sorry for the delay and for the hassle
