### ISSUE TITLE
Add belgianairways.com

### ISSUE THREAD

**Issue by kenlju** [disposable-email-domains/disposable-email-domains#509]
Has been used in scripting for creating fake accounts

**Comment by kenlju** [comment]
Domain exists in other lists.

https://github.com/beeyev/disposable-email-filter-php/releases/tag/v1.3.15

https://www.usercheck.com/domain/belgianairways.com?ref=mailcheck

https://verifymail.io/domain/belgianairways.com

**Comment by martenson** [comment]
@kenlju This repo gathers domains that offer services of disposable email provider. Please point at a place where I can create a disposable email with `@belgianairways.com` or close this issue.

**Comment by martenson** [comment]
dupe of #501
