### ISSUE TITLE
Add New Disposable Email Domains and Improve Documentation

### ISSUE THREAD

**Issue by sidinsearch** [disposable-email-domains/disposable-email-domains#517]
Hello, I'd like to contribute to this project for Hacktoberfest 2024 by:
Researching and adding new disposable email domains that are currently in use but not yet included in the list.
Enhancing the README.md file to include more detailed contribution guidelines, usage examples, and best practices for integrating this list into different systems.
Please assign this issue to me under Hacktoberfest. 
Thank you!

**Comment by martenson** [comment]
@sidinsearch howdy! Thanks for your interest, some important and isolated issues for hacktoberfest would be: https://github.com/disposable-email-domains/disposable-email-domains/issues/450 and https://github.com/disposable-email-domains/disposable-email-domains/issues/456

**Comment by sidinsearch** [comment]
Thank you for the opportunity! I’m ready to work on both issues #450 and #456. Please assign them to me under Hacktoberfest, and I’ll start contributing right away.

**Comment by martenson** [comment]
@sidinsearch please consider yourself assigned to them

**Comment by sidinsearch** [comment]
currently not have the time but whenever possible , i am there to work on this project
