### ISSUE TITLE
Add DuckDuckGo Privacy Email aliases

### ISSUE THREAD

**Issue by tiagorangel2011** [disposable-email-domains/disposable-email-domains#518]
Add DuckDuckGo Privacy Email aliases

**Comment by martenson** [comment]
> No, private Duck Addresses do not expire. Email sent to a private Duck Address will continue to forward to your inbox as long as your Email Protection account is active, and you have not deactivated the private Duck Address.

also see https://github.com/disposable-email-domains/disposable-email-domains/pull/298
