### ISSUE TITLE
New domain: tempmail.so

### ISSUE THREAD

**Issue by iredmail** [disposable-email-domains/disposable-email-domains#520]

**Comment by martenson** [comment]
https://github.com/disposable-email-domains/disposable-email-domains/commit/bd843a9cbb8135584a9463ded4d4b67237ddc5be

**Comment by iredmail** [comment]
Hi @martenson,

The commit added `mailnuo.com`, not the one i mentioned: `tempmail.so`.

**Comment by martenson** [comment]
@iredmail where do I get @tempmail.so address?
