### ISSUE TITLE
RFC: enable repo sponsorship

### ISSUE THREAD

**Issue by martenson** [disposable-email-domains/disposable-email-domains#534]
Hey @di & @deguif,
lately I found myself without enough time and motivation to manage the PRs and issues of this repo properly which decreases its value to the community. I am now considering enabling github sponsorship so maybe I get occasionally some change for coffee which I can in turn convert into PR reviews and maybe automating some of the scraping.
Since we are co-maintainers I'd like to hear your opinions about this.
Cheers,
M.

**Comment by di** [comment]
Fine with me!

**Comment by martenson** [comment]
I reached out to @deguif privately but received no response. I'll assume they do not care either way.

**Comment by martenson** [comment]
sponsorship is now enabled
